# Generated by Django 5.2.7 on 2025-11-06 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=100)),
                ('FROM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to=settings.AUTH_USER_MODEL)),
                ('TO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_freelancers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_client')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_job_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('cost', models.BigIntegerField()),
                ('FREELANCER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_freelancers')),
                ('JOB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_job')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_daily_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('report_status', models.CharField(max_length=500)),
                ('JOB_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_job_request')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('JOB_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_job_request')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_client')),
                ('FREELANCER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_freelancers')),
            ],
        ),
    ]
